export const ENV = {
	NODE_TLS_REJECT_UNAUTHORIZED: 'NODE_TLS_REJECT_UNAUTHORIZED',
	NODE_ENV: 'NODE_ENV',

	HOST: 'HOST',
	PORT: 'PORT',
	BASE_PATH: 'BASE_PATH',

	CATS_SERVICE: 'CATS_SERVICE',
	DOGS_SERVICE: 'DOGS_SERVICE',
} as const;
